name = "electricity-tracker"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Custom domain routes
routes = [
  { pattern = "powermeter.app", custom_domain = true },
  { pattern = "www.powermeter.app", custom_domain = true }
]

[assets]
directory = "./public"

# Environment variables
[vars]
FROM_EMAIL = "noreply@powermeter.app"

# D1 Database binding
[[d1_databases]]
binding = "DB"  # This should match what you use in your code
database_name = "electricity-tracker-db"
database_id = "fbcc393d-4801-4fd1-a090-5dca1fa3ee92"

# Secrets (use 'wrangler secret put' to set these)
# JWT_SECRET - Set via: wrangler secret put JWT_SECRET
# RESEND_API_KEY - Set via: wrangler secret put RESEND_API_KEY

# Worker analytics (uncomment to enable)
# [[analytics_engine_datasets]]
# binding = "AE"

# Optional: KV namespace bindings (if you use KV storage)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"

# Build configuration (uncomment to enable)
# [build]
# command = ""  # Add build command if needed
# cwd = ""      # Change if your code is in a subdirectory